import React from 'react';
import Layout from '../../components/layout/Layout';
import './TermsAndConditions.css'

function TermsAndConditions() {
    return(
        <div>
            <Layout>
                <div className='contentContainer'>
                    <h1>Termeni si conditii</h1>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sollicitudin nisl a vulputate vulputate. Nam non quam eget lorem congue consequat. Vestibulum lobortis imperdiet risus, sit amet hendrerit ipsum gravida ac. Nullam id est tincidunt, vehicula elit non, finibus ex. Nulla mollis elit tortor, et ultricies leo malesuada eget. Suspendisse egestas leo in nulla vehicula, eget facilisis quam fermentum. Aenean pharetra lacus ac dignissim ultrices. Sed tortor velit, ultricies imperdiet porta a, molestie sit amet quam.
                        Donec non lectus dapibus, commodo eros nec, accumsan orci. Duis et tellus non orci convallis convallis nec vel ante. Mauris ultrices magna vel accumsan faucibus. Sed urna lacus, venenatis ac laoreet quis, convallis id libero. Cras luctus nibh a nisi efficitur, non pulvinar nunc fermentum. Nam vel sapien non lorem facilisis fringilla eu vel nulla. Fusce ultrices tempus magna. In iaculis metus a mollis hendrerit.
                        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam aliquam imperdiet ipsum vel interdum. Morbi in gravida tellus. Proin lobortis faucibus enim quis feugiat. Aenean ex nisl, lacinia eget bibendum eget, porta id augue. Quisque vitae nisl quam. Pellentesque facilisis erat ac ex vulputate venenatis. Aenean libero arcu, facilisis auctor tristique ac, malesuada in ex. Donec tempus metus erat, eget laoreet felis tempor non. Curabitur lacus augue, dictum ac massa et, rutrum euismod nisi. Mauris lectus ex, pretium eu posuere a, ullamcorper quis sem. Integer tristique euismod neque, eu laoreet diam cursus blandit.
                        In id suscipit enim. Proin augue metus, commodo nec elit in, tempor suscipit leo. Integer lobortis nulla sit amet nisl laoreet dapibus. Praesent ullamcorper ante quis rutrum auctor. Aenean aliquam rutrum vulputate. Vestibulum commodo ligula nec accumsan euismod. Nam vel lectus sagittis, condimentum augue ut, auctor felis. Nulla maximus felis arcu, sed consequat augue malesuada sit amet. Sed imperdiet nisl iaculis scelerisque vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc tincidunt lacus odio, eget ullamcorper risus fringilla sed. Nullam a ante diam. Vivamus ac sem vel nulla commodo fringilla. Vivamus molestie sapien et felis sollicitudin, quis lobortis turpis tempus.
                        In hac habitasse platea dictumst. Proin non pretium urna, et convallis lacus. Vestibulum scelerisque, tellus quis viverra sollicitudin, lacus erat porta nulla, et pretium purus nunc tincidunt nulla. Cras pellentesque sagittis arcu vitae sollicitudin. In felis tortor, blandit non venenatis a, posuere ut eros. Pellentesque eget eleifend ante. Ut ac urna felis. Nunc fermentum venenatis aliquam.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sollicitudin nisl a vulputate vulputate. Nam non quam eget lorem congue consequat. Vestibulum lobortis imperdiet risus, sit amet hendrerit ipsum gravida ac. Nullam id est tincidunt, vehicula elit non, finibus ex. Nulla mollis elit tortor, et ultricies leo malesuada eget. Suspendisse egestas leo in nulla vehicula, eget facilisis quam fermentum. Aenean pharetra lacus ac dignissim ultrices. Sed tortor velit, ultricies imperdiet porta a, molestie sit amet quam.
                        Donec non lectus dapibus, commodo eros nec, accumsan orci. Duis et tellus non orci convallis convallis nec vel ante. Mauris ultrices magna vel accumsan faucibus. Sed urna lacus, venenatis ac laoreet quis, convallis id libero. Cras luctus nibh a nisi efficitur, non pulvinar nunc fermentum. Nam vel sapien non lorem facilisis fringilla eu vel nulla. Fusce ultrices tempus magna. In iaculis metus a mollis hendrerit.
                        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam aliquam imperdiet ipsum vel interdum. Morbi in gravida tellus. Proin lobortis faucibus enim quis feugiat. Aenean ex nisl, lacinia eget bibendum eget, porta id augue. Quisque vitae nisl quam. Pellentesque facilisis erat ac ex vulputate venenatis. Aenean libero arcu, facilisis auctor tristique ac, malesuada in ex. Donec tempus metus erat, eget laoreet felis tempor non. Curabitur lacus augue, dictum ac massa et, rutrum euismod nisi. Mauris lectus ex, pretium eu posuere a, ullamcorper quis sem. Integer tristique euismod neque, eu laoreet diam cursus blandit.
                        In id suscipit enim. Proin augue metus, commodo nec elit in, tempor suscipit leo. Integer lobortis nulla sit amet nisl laoreet dapibus. Praesent ullamcorper ante quis rutrum auctor. Aenean aliquam rutrum vulputate. Vestibulum commodo ligula nec accumsan euismod. Nam vel lectus sagittis, condimentum augue ut, auctor felis. Nulla maximus felis arcu, sed consequat augue malesuada sit amet. Sed imperdiet nisl iaculis scelerisque vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc tincidunt lacus odio, eget ullamcorper risus fringilla sed. Nullam a ante diam. Vivamus ac sem vel nulla commodo fringilla. Vivamus molestie sapien et felis sollicitudin, quis lobortis turpis tempus.
                        In hac habitasse platea dictumst. Proin non pretium urna, et convallis lacus. Vestibulum scelerisque, tellus quis viverra sollicitudin, lacus erat porta nulla, et pretium purus nunc tincidunt nulla. Cras pellentesque sagittis arcu vitae sollicitudin. In felis tortor, blandit non venenatis a, posuere ut eros. Pellentesque eget eleifend ante. Ut ac urna felis. Nunc fermentum venenatis aliquam.
                    </p>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sollicitudin nisl a vulputate vulputate. Nam non quam eget lorem congue consequat. Vestibulum lobortis imperdiet risus, sit amet hendrerit ipsum gravida ac. Nullam id est tincidunt, vehicula elit non, finibus ex. Nulla mollis elit tortor, et ultricies leo malesuada eget. Suspendisse egestas leo in nulla vehicula, eget facilisis quam fermentum. Aenean pharetra lacus ac dignissim ultrices. Sed tortor velit, ultricies imperdiet porta a, molestie sit amet quam.
                        Donec non lectus dapibus, commodo eros nec, accumsan orci. Duis et tellus non orci convallis convallis nec vel ante. Mauris ultrices magna vel accumsan faucibus. Sed urna lacus, venenatis ac laoreet quis, convallis id libero. Cras luctus nibh a nisi efficitur, non pulvinar nunc fermentum. Nam vel sapien non lorem facilisis fringilla eu vel nulla. Fusce ultrices tempus magna. In iaculis metus a mollis hendrerit.
                        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam aliquam imperdiet ipsum vel interdum. Morbi in gravida tellus. Proin lobortis faucibus enim quis feugiat. Aenean ex nisl, lacinia eget bibendum eget, porta id augue. Quisque vitae nisl quam. Pellentesque facilisis erat ac ex vulputate venenatis. Aenean libero arcu, facilisis auctor tristique ac, malesuada in ex. Donec tempus metus erat, eget laoreet felis tempor non. Curabitur lacus augue, dictum ac massa et, rutrum euismod nisi. Mauris lectus ex, pretium eu posuere a, ullamcorper quis sem. Integer tristique euismod neque, eu laoreet diam cursus blandit.
                        In id suscipit enim. Proin augue metus, commodo nec elit in, tempor suscipit leo. Integer lobortis nulla sit amet nisl laoreet dapibus. Praesent ullamcorper ante quis rutrum auctor. Aenean aliquam rutrum vulputate. Vestibulum commodo ligula nec accumsan euismod. Nam vel lectus sagittis, condimentum augue ut, auctor felis. Nulla maximus felis arcu, sed consequat augue malesuada sit amet. Sed imperdiet nisl iaculis scelerisque vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc tincidunt lacus odio, eget ullamcorper risus fringilla sed. Nullam a ante diam. Vivamus ac sem vel nulla commodo fringilla. Vivamus molestie sapien et felis sollicitudin, quis lobortis turpis tempus.
                        In hac habitasse platea dictumst. Proin non pretium urna, et convallis lacus. Vestibulum scelerisque, tellus quis viverra sollicitudin, lacus erat porta nulla, et pretium purus nunc tincidunt nulla. Cras pellentesque sagittis arcu vitae sollicitudin. In felis tortor, blandit non venenatis a, posuere ut eros. Pellentesque eget eleifend ante. Ut ac urna felis. Nunc fermentum venenatis aliquam.
                    </p>
                </div>
                </Layout>
        </div>
    );
}

export default TermsAndConditions;